server:
  port: 8080
spring:
  application:
    name: mybatis-assoaction
  datasource:
    url: jdbc:mysql://localhost:3306/assoaction?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.wpw.mybatisasscaction.entity